# Generated by Django 4.0.1 on 2022-02-12 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tution', '0004_post_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='media/tution/image'),
        ),
    ]
