# Generated by Django 4.0.1 on 2022-02-13 05:45

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tution', '0005_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='medium',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Bangla', 'bangla'), ('English', 'English'), ('Urdu', 'Urdu'), ('Arabic', 'Arabic'), ('Hindi', 'Hindi')], default='bangla', max_length=100),
        ),
    ]
